In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [9]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [10]:
dependent=dataset[['charges']]

In [12]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [14]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test=train_test_split(independent, dependent , test_size=0.30, random_state=0)

In [15]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\ragav\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\ragav\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
    --------------------------------------- 2.1/101.7 MB 9.3 MB/s eta 0:00:11
   - -------------------------------------- 3.1/101.7 MB 7.2 MB/s eta 0:00:14
   - -------------------------------------- 4.7/101.7 MB 7.3 MB/s eta 0:00:14
   -- ------------------------------------- 6.0/101.7 MB 7.0 MB/s eta 0:00:14
   -- ------------------------------------- 7.3/101.7 MB 6.9 MB/s eta 0:00:14
   --- ------------------------------------ 8.7/101.7 MB 6.8 MB/s eta 0:00:14
   --- ------------------------------------ 10.0/101.7 MB 6.7 MB/s eta 0:00:14
   ---- ----------------------------------- 11.3/101.7 MB 6.6 MB/s eta 0:00:14
   ---- ----------------------------------- 12.6/101.7 MB 6.6 MB/s eta 0:00:14
   ----- ---------------------------------- 13.9/101.7 MB 6.6 MB/s eta 0:00:14
   ----- ---------------------------------- 15.2/101.7 MB 6.5 MB/s eta 0:00:14
   ------ --------------------------------- 16.5/101.7 MB 6.5 MB/s eta 0:00:14
   ------- -------------------------------- 17.8/101.7 MB 6.5 MB/s eta 0:00:13
   ------- -------------------------------- 19.1/101.7 MB 6.5 MB/s eta 0:00:13
   -------- ------------------------------- 20.4/101.7 MB 6.5 MB/s eta 0:00:13
   -------- ------------------------------- 21.8/101.7 MB 6.5 MB/s eta 0:00:13
   --------- ------------------------------ 23.1/101.7 MB 6.5 MB/s eta 0:00:13
   --------- ------------------------------ 24.4/101.7 MB 6.4 MB/s eta 0:00:13
   ---------- ----------------------------- 25.7/101.7 MB 6.4 MB/s eta 0:00:12
   ---------- ----------------------------- 26.7/101.7 MB 6.4 MB/s eta 0:00:12
   ---------- ----------------------------- 27.5/101.7 MB 6.3 MB/s eta 0:00:12
   ----------- ---------------------------- 28.0/101.7 MB 6.2 MB/s eta 0:00:12
   ----------- ---------------------------- 28.6/101.7 MB 5.9 MB/s eta 0:00:13
   ----------- ---------------------------- 29.4/101.7 MB 5.8 MB/s eta 0:00:13
   ----------- ---------------------------- 30.1/101.7 MB 5.7 MB/s eta 0:00:13
   ------------ --------------------------- 31.2/101.7 MB 5.7 MB/s eta 0:00:13
   ------------ --------------------------- 32.2/101.7 MB 5.7 MB/s eta 0:00:13
   ------------- -------------------------- 33.3/101.7 MB 5.7 MB/s eta 0:00:13
   ------------- -------------------------- 34.9/101.7 MB 5.7 MB/s eta 0:00:12
   -------------- ------------------------- 36.2/101.7 MB 5.7 MB/s eta 0:00:12
   -------------- ------------------------- 37.7/101.7 MB 5.8 MB/s eta 0:00:12
   --------------- ------------------------ 39.1/101.7 MB 5.8 MB/s eta 0:00:11
   --------------- ------------------------ 40.4/101.7 MB 5.8 MB/s eta 0:00:11
   ---------------- ----------------------- 41.7/101.7 MB 5.8 MB/s eta 0:00:11
   ---------------- ----------------------- 43.0/101.7 MB 5.9 MB/s eta 0:00:11
   ----------------- ---------------------- 44.3/101.7 MB 5.9 MB/s eta 0:00:10
   ------------------ --------------------- 45.9/101.7 MB 5.9 MB/s eta 0:00:10
   ------------------ --------------------- 47.2/101.7 MB 5.9 MB/s eta 0:00:10
   ------------------- -------------------- 48.5/101.7 MB 5.9 MB/s eta 0:00:09
   ------------------- -------------------- 49.8/101.7 MB 5.9 MB/s eta 0:00:09
   -------------------- ------------------- 51.1/101.7 MB 5.9 MB/s eta 0:00:09
   -------------------- ------------------- 52.2/101.7 MB 5.9 MB/s eta 0:00:09
   -------------------- ------------------- 53.2/101.7 MB 5.9 MB/s eta 0:00:09
   --------------------- ------------------ 54.0/101.7 MB 5.9 MB/s eta 0:00:09
   --------------------- ------------------ 54.8/101.7 MB 5.8 MB/s eta 0:00:09
   --------------------- ------------------ 55.6/101.7 MB 5.8 MB/s eta 0:00:09
   ---------------------- ----------------- 56.4/101.7 MB 5.7 MB/s eta 0:00:08
   ---------------------- ----------------- 57.4/101.7 MB 5.7 MB/s eta 0:00:08
   ----------------------- ---------------- 58.7/101.7 MB 5.7 MB/s eta 0:00:08
   ----------------------- ---------------- 59.8/101.7 MB 5.7 MB/s eta 0:00:08
   ------------------------ --------------- 61.1/101.7 MB 5.7 MB/s eta 0:00:08
   ------------------------ --------------- 62.4/101.7 MB 5.7 MB/s eta 0:00:07
   ------------------------- -------------- 63.7/101.7 MB 5.7 MB/s eta 0:00:07
   ------------------------- -------------- 65.3/101.7 MB 5.8 MB/s eta 0:00:07
   -------------------------- ------------- 66.8/101.7 MB 5.8 MB/s eta 0:00:07
   -------------------------- ------------- 68.2/101.7 MB 5.8 MB/s eta 0:00:06
   --------------------------- ------------ 69.5/101.7 MB 5.8 MB/s eta 0:00:06
   --------------------------- ------------ 70.8/101.7 MB 5.8 MB/s eta 0:00:06
   ---------------------------- ----------- 72.1/101.7 MB 5.8 MB/s eta 0:00:06
   ---------------------------- ----------- 73.4/101.7 MB 5.8 MB/s eta 0:00:05
   ----------------------------- ---------- 74.7/101.7 MB 5.8 MB/s eta 0:00:05
   ----------------------------- ---------- 76.0/101.7 MB 5.9 MB/s eta 0:00:05
   ------------------------------ --------- 77.3/101.7 MB 5.9 MB/s eta 0:00:05
   ------------------------------ --------- 78.6/101.7 MB 5.9 MB/s eta 0:00:04
   ------------------------------- -------- 79.7/101.7 MB 5.9 MB/s eta 0:00:04
   ------------------------------- -------- 80.7/101.7 MB 5.9 MB/s eta 0:00:04
   -------------------------------- ------- 82.1/101.7 MB 5.8 MB/s eta 0:00:04
   -------------------------------- ------- 82.8/101.7 MB 5.8 MB/s eta 0:00:04
   -------------------------------- ------- 83.6/101.7 MB 5.8 MB/s eta 0:00:04
   --------------------------------- ------ 84.1/101.7 MB 5.8 MB/s eta 0:00:04
   --------------------------------- ------ 84.7/101.7 MB 5.7 MB/s eta 0:00:03
   --------------------------------- ------ 85.2/101.7 MB 5.7 MB/s eta 0:00:03
   --------------------------------- ------ 85.7/101.7 MB 5.6 MB/s eta 0:00:03
   --------------------------------- ------ 86.2/101.7 MB 5.6 MB/s eta 0:00:03
   ---------------------------------- ----- 87.0/101.7 MB 5.6 MB/s eta 0:00:03
   ---------------------------------- ----- 87.8/101.7 MB 5.5 MB/s eta 0:00:03
   ---------------------------------- ----- 88.6/101.7 MB 5.5 MB/s eta 0:00:03
   ----------------------------------- ---- 89.7/101.7 MB 5.5 MB/s eta 0:00:03
   ----------------------------------- ---- 90.7/101.7 MB 5.5 MB/s eta 0:00:02
   ------------------------------------ --- 92.0/101.7 MB 5.5 MB/s eta 0:00:02
   ------------------------------------ --- 93.3/101.7 MB 5.5 MB/s eta 0:00:02
   ------------------------------------- -- 94.4/101.7 MB 5.5 MB/s eta 0:00:02
   ------------------------------------- -- 95.4/101.7 MB 5.5 MB/s eta 0:00:02
   ------------------------------------- -- 96.5/101.7 MB 5.5 MB/s eta 0:00:01
   -------------------------------------- - 97.8/101.7 MB 5.5 MB/s eta 0:00:01
   -------------------------------------- - 99.1/101.7 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------  100.7/101.7 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 5.5 MB/s  0:00:18
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [16]:
import xgboost as xgb

In [17]:
regressor = xgb.XGBRegressor(
    n_estimators=200,      # number of trees
    learning_rate=0.05,    # shrinkage factor
    max_depth=4,           # depth of each tree
    subsample=0.8,         # fraction of samples used per tree
    colsample_bytree=0.8,  # fraction of features used per tree
    random_state=42 )

In [18]:
regressor.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [19]:
y_pred=regressor.predict(x_test)

In [20]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test, y_pred)

In [21]:
r_score

0.8798794746398926